using System.Collections.Generic;

namespace Models
{
    public class GroupMembers
    {

        public int Id { get; set; } // Line Id generated by database
        
        public int GroupId { get; set; } //For GroupId column 

        public int MemberUserId { get; set; } //For MemberUserId column

        public string GroupName { get; set; }
        
        //Do we store relationships here?
        //public List<Group> Groups { get; set; } //For relationship

        //public List<User> User { get; set; } //For relationship
    }

}


